import { Inter } from "next/font/google";
import "@/app/globals.css";
import Squares from "@/components/Squares";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sherwin Rodriguez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased relative bg-[#0a1a3c]`}>
        <div className="fixed inset-0 -z-10 w-full h-full bg-[#020107]">
          <Squares 
            speed={0.5} 
            squareSize={500}
            direction="diagonal"
            borderColor="#fff"
            hoverFillColor="#132a4d"
          />
        </div>
        <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:p-8">
          {children}
        </div>
      </body>
    </html>
  );
}
